sbatch process.batch ./batches/FORECasT_11.json
sbatch process.batch ./batches/FORECasT_12.json
sbatch process.batch ./batches/FORECasT_13.json
sbatch process.batch ./batches/FORECasT_14.json
sbatch process.batch ./batches/FORECasT_15.json
sbatch process.batch ./batches/FORECasT_16.json
sbatch process.batch ./batches/FORECasT_17.json
sbatch process.batch ./batches/FORECasT_18.json
sbatch process.batch ./batches/FORECasT_19.json
sbatch process.batch ./batches/FORECasT_20.json
sbatch process.batch ./batches/FORECasT_21.json
sbatch process.batch ./batches/FORECasT_22.json
sbatch process.batch ./batches/FORECasT_23.json
sbatch process.batch ./batches/FORECasT_24.json
sbatch process.batch ./batches/FORECasT_25.json
sbatch process.batch ./batches/FORECasT_26.json
sbatch process.batch ./batches/FORECasT_27.json
sbatch process.batch ./batches/FORECasT_28.json
sbatch process.batch ./batches/FORECasT_29.json
sbatch process.batch ./batches/FORECasT_30.json
sbatch process.batch ./batches/FORECasT_31.json
sbatch process.batch ./batches/FORECasT_32.json
sbatch process.batch ./batches/FORECasT_33.json
sbatch process.batch ./batches/FORECasT_34.json
sbatch process.batch ./batches/FORECasT_35.json
sbatch process.batch ./batches/FORECasT_36.json
sbatch process.batch ./batches/FORECasT_37.json
sbatch process.batch ./batches/FORECasT_38.json
sbatch process.batch ./batches/FORECasT_39.json
sbatch process.batch ./batches/FORECasT_40.json
sbatch process.batch ./batches/FORECasT_41.json
sbatch process.batch ./batches/FORECasT_42.json
sbatch process.batch ./batches/FORECasT_43.json
sbatch process.batch ./batches/FORECasT_44.json
sbatch process.batch ./batches/FORECasT_45.json
sbatch process.batch ./batches/FORECasT_46.json
sbatch process.batch ./batches/FORECasT_47.json
sbatch process.batch ./batches/FORECasT_48.json
sbatch process.batch ./batches/FORECasT_49.json
sbatch process.batch ./batches/FORECasT_50.json
sbatch process.batch ./batches/FORECasT_51.json
sbatch process.batch ./batches/FORECasT_52.json
sbatch process.batch ./batches/FORECasT_53.json
sbatch process.batch ./batches/FORECasT_54.json
sbatch process.batch ./batches/FORECasT_55.json
sbatch process.batch ./batches/FORECasT_56.json
sbatch process.batch ./batches/FORECasT_57.json
sbatch process.batch ./batches/FORECasT_58.json
sbatch process.batch ./batches/FORECasT_59.json
sbatch process.batch ./batches/FORECasT_60.json
sbatch process.batch ./batches/FORECasT_61.json
sbatch process.batch ./batches/FORECasT_62.json
sbatch process.batch ./batches/FORECasT_63.json
sbatch process.batch ./batches/FORECasT_64.json
sbatch process.batch ./batches/FORECasT_65.json
sbatch process.batch ./batches/FORECasT_66.json
sbatch process.batch ./batches/FORECasT_67.json
sbatch process.batch ./batches/FORECasT_68.json
sbatch process.batch ./batches/FORECasT_69.json
sbatch process.batch ./batches/FORECasT_70.json
sbatch process.batch ./batches/FORECasT_71.json
sbatch process.batch ./batches/FORECasT_72.json
sbatch process.batch ./batches/FORECasT_73.json
sbatch process.batch ./batches/FORECasT_74.json
sbatch process.batch ./batches/FORECasT_75.json
sbatch process.batch ./batches/FORECasT_76.json
sbatch process.batch ./batches/FORECasT_77.json
sbatch process.batch ./batches/FORECasT_78.json
sbatch process.batch ./batches/FORECasT_79.json
sbatch process.batch ./batches/FORECasT_80.json
sbatch process.batch ./batches/FORECasT_81.json
sbatch process.batch ./batches/FORECasT_82.json
sbatch process.batch ./batches/FORECasT_83.json
sbatch process.batch ./batches/FORECasT_84.json
sbatch process.batch ./batches/FORECasT_85.json
sbatch process.batch ./batches/FORECasT_86.json
sbatch process.batch ./batches/FORECasT_87.json
sbatch process.batch ./batches/FORECasT_88.json
sbatch process.batch ./batches/FORECasT_89.json
sbatch process.batch ./batches/FORECasT_90.json
sbatch process.batch ./batches/FORECasT_91.json
sbatch process.batch ./batches/FORECasT_92.json
sbatch process.batch ./batches/FORECasT_93.json
sbatch process.batch ./batches/FORECasT_94.json
sbatch process.batch ./batches/FORECasT_95.json
sbatch process.batch ./batches/FORECasT_96.json
sbatch process.batch ./batches/FORECasT_97.json
sbatch process.batch ./batches/FORECasT_98.json
sbatch process.batch ./batches/FORECasT_99.json
sbatch process.batch ./batches/FORECasT_100.json
sbatch process.batch ./batches/FORECasT_101.json
sbatch process.batch ./batches/FORECasT_102.json
sbatch process.batch ./batches/FORECasT_103.json
sbatch process.batch ./batches/FORECasT_104.json
sbatch process.batch ./batches/FORECasT_105.json
sbatch process.batch ./batches/FORECasT_106.json
sbatch process.batch ./batches/FORECasT_107.json
sbatch process.batch ./batches/FORECasT_108.json
sbatch process.batch ./batches/FORECasT_109.json
sbatch process.batch ./batches/FORECasT_110.json
sbatch process.batch ./batches/FORECasT_111.json
sbatch process.batch ./batches/FORECasT_112.json
sbatch process.batch ./batches/FORECasT_113.json
sbatch process.batch ./batches/FORECasT_114.json
sbatch process.batch ./batches/FORECasT_115.json
sbatch process.batch ./batches/FORECasT_116.json
sbatch process.batch ./batches/FORECasT_117.json
sbatch process.batch ./batches/FORECasT_118.json
sbatch process.batch ./batches/FORECasT_119.json
sbatch process.batch ./batches/FORECasT_120.json
sbatch process.batch ./batches/FORECasT_121.json
sbatch process.batch ./batches/FORECasT_122.json
sbatch process.batch ./batches/FORECasT_123.json
sbatch process.batch ./batches/FORECasT_124.json
sbatch process.batch ./batches/FORECasT_125.json
sbatch process.batch ./batches/FORECasT_126.json
sbatch process.batch ./batches/FORECasT_127.json
sbatch process.batch ./batches/FORECasT_128.json
sbatch process.batch ./batches/FORECasT_129.json
sbatch process.batch ./batches/FORECasT_130.json
sbatch process.batch ./batches/FORECasT_131.json
sbatch process.batch ./batches/FORECasT_132.json
sbatch process.batch ./batches/FORECasT_133.json
sbatch process.batch ./batches/FORECasT_134.json
sbatch process.batch ./batches/FORECasT_135.json
sbatch process.batch ./batches/FORECasT_136.json
sbatch process.batch ./batches/FORECasT_137.json
sbatch process.batch ./batches/FORECasT_138.json
sbatch process.batch ./batches/FORECasT_139.json
sbatch process.batch ./batches/FORECasT_140.json
sbatch process.batch ./batches/FORECasT_141.json
sbatch process.batch ./batches/FORECasT_142.json
sbatch process.batch ./batches/FORECasT_143.json
sbatch process.batch ./batches/FORECasT_144.json
sbatch process.batch ./batches/FORECasT_145.json
sbatch process.batch ./batches/FORECasT_146.json
sbatch process.batch ./batches/FORECasT_147.json
sbatch process.batch ./batches/FORECasT_148.json
sbatch process.batch ./batches/FORECasT_149.json
sbatch process.batch ./batches/FORECasT_150.json
sbatch process.batch ./batches/FORECasT_151.json
sbatch process.batch ./batches/FORECasT_152.json
sbatch process.batch ./batches/FORECasT_153.json
sbatch process.batch ./batches/FORECasT_154.json
sbatch process.batch ./batches/FORECasT_155.json
sbatch process.batch ./batches/FORECasT_156.json
sbatch process.batch ./batches/FORECasT_157.json
sbatch process.batch ./batches/FORECasT_158.json
sbatch process.batch ./batches/FORECasT_159.json
sbatch process.batch ./batches/FORECasT_160.json
sbatch process.batch ./batches/FORECasT_161.json
sbatch process.batch ./batches/FORECasT_162.json
sbatch process.batch ./batches/FORECasT_163.json
sbatch process.batch ./batches/FORECasT_164.json
sbatch process.batch ./batches/FORECasT_165.json
sbatch process.batch ./batches/FORECasT_166.json
sbatch process.batch ./batches/FORECasT_167.json
sbatch process.batch ./batches/FORECasT_168.json
sbatch process.batch ./batches/FORECasT_169.json
sbatch process.batch ./batches/FORECasT_170.json
sbatch process.batch ./batches/FORECasT_171.json
sbatch process.batch ./batches/FORECasT_172.json
sbatch process.batch ./batches/FORECasT_173.json
sbatch process.batch ./batches/FORECasT_174.json
sbatch process.batch ./batches/FORECasT_175.json
sbatch process.batch ./batches/FORECasT_176.json
sbatch process.batch ./batches/FORECasT_177.json
sbatch process.batch ./batches/FORECasT_178.json
sbatch process.batch ./batches/FORECasT_179.json
sbatch process.batch ./batches/FORECasT_180.json
sbatch process.batch ./batches/FORECasT_181.json
sbatch process.batch ./batches/FORECasT_182.json
sbatch process.batch ./batches/FORECasT_183.json
sbatch process.batch ./batches/FORECasT_184.json
sbatch process.batch ./batches/FORECasT_185.json
sbatch process.batch ./batches/FORECasT_186.json
sbatch process.batch ./batches/FORECasT_187.json
sbatch process.batch ./batches/FORECasT_188.json
sbatch process.batch ./batches/FORECasT_189.json
sbatch process.batch ./batches/FORECasT_190.json
sbatch process.batch ./batches/FORECasT_191.json
sbatch process.batch ./batches/FORECasT_192.json
sbatch process.batch ./batches/FORECasT_193.json
sbatch process.batch ./batches/FORECasT_194.json
sbatch process.batch ./batches/FORECasT_195.json
sbatch process.batch ./batches/FORECasT_196.json
sbatch process.batch ./batches/FORECasT_197.json
sbatch process.batch ./batches/FORECasT_198.json
sbatch process.batch ./batches/FORECasT_199.json
sbatch process.batch ./batches/FORECasT_200.json
sbatch process.batch ./batches/FORECasT_201.json
sbatch process.batch ./batches/FORECasT_202.json
sbatch process.batch ./batches/FORECasT_203.json
sbatch process.batch ./batches/FORECasT_204.json
sbatch process.batch ./batches/FORECasT_205.json
sbatch process.batch ./batches/FORECasT_206.json
sbatch process.batch ./batches/FORECasT_207.json
sbatch process.batch ./batches/FORECasT_208.json
sbatch process.batch ./batches/FORECasT_209.json
sbatch process.batch ./batches/FORECasT_210.json
sbatch process.batch ./batches/FORECasT_211.json
sbatch process.batch ./batches/FORECasT_212.json
sbatch process.batch ./batches/FORECasT_213.json
sbatch process.batch ./batches/FORECasT_214.json
sbatch process.batch ./batches/FORECasT_215.json
sbatch process.batch ./batches/FORECasT_216.json
sbatch process.batch ./batches/FORECasT_217.json
sbatch process.batch ./batches/FORECasT_218.json
sbatch process.batch ./batches/FORECasT_219.json
sbatch process.batch ./batches/FORECasT_220.json
sbatch process.batch ./batches/FORECasT_221.json
sbatch process.batch ./batches/FORECasT_222.json
sbatch process.batch ./batches/FORECasT_223.json
sbatch process.batch ./batches/FORECasT_224.json
sbatch process.batch ./batches/FORECasT_225.json
sbatch process.batch ./batches/FORECasT_226.json
sbatch process.batch ./batches/FORECasT_227.json
sbatch process.batch ./batches/FORECasT_228.json
sbatch process.batch ./batches/FORECasT_229.json
sbatch process.batch ./batches/FORECasT_230.json
sbatch process.batch ./batches/FORECasT_231.json
sbatch process.batch ./batches/FORECasT_232.json
sbatch process.batch ./batches/FORECasT_233.json
sbatch process.batch ./batches/FORECasT_234.json
sbatch process.batch ./batches/FORECasT_235.json
sbatch process.batch ./batches/FORECasT_236.json
sbatch process.batch ./batches/FORECasT_237.json
sbatch process.batch ./batches/FORECasT_238.json
sbatch process.batch ./batches/FORECasT_239.json
sbatch process.batch ./batches/FORECasT_240.json
sbatch process.batch ./batches/FORECasT_241.json
sbatch process.batch ./batches/FORECasT_242.json
sbatch process.batch ./batches/FORECasT_243.json
sbatch process.batch ./batches/FORECasT_244.json
sbatch process.batch ./batches/FORECasT_245.json
sbatch process.batch ./batches/FORECasT_246.json
sbatch process.batch ./batches/FORECasT_247.json
sbatch process.batch ./batches/FORECasT_248.json
sbatch process.batch ./batches/FORECasT_249.json
sbatch process.batch ./batches/FORECasT_250.json
sbatch process.batch ./batches/FORECasT_251.json
sbatch process.batch ./batches/FORECasT_252.json
sbatch process.batch ./batches/FORECasT_253.json
sbatch process.batch ./batches/FORECasT_254.json
sbatch process.batch ./batches/FORECasT_255.json
sbatch process.batch ./batches/FORECasT_256.json
sbatch process.batch ./batches/FORECasT_257.json
sbatch process.batch ./batches/FORECasT_258.json
sbatch process.batch ./batches/FORECasT_259.json
sbatch process.batch ./batches/FORECasT_260.json
sbatch process.batch ./batches/FORECasT_261.json
sbatch process.batch ./batches/FORECasT_262.json
sbatch process.batch ./batches/FORECasT_263.json
sbatch process.batch ./batches/FORECasT_264.json
sbatch process.batch ./batches/FORECasT_265.json
sbatch process.batch ./batches/FORECasT_266.json
sbatch process.batch ./batches/FORECasT_267.json
sbatch process.batch ./batches/FORECasT_268.json
sbatch process.batch ./batches/FORECasT_269.json
sbatch process.batch ./batches/FORECasT_270.json
sbatch process.batch ./batches/FORECasT_271.json
sbatch process.batch ./batches/FORECasT_272.json
sbatch process.batch ./batches/FORECasT_273.json
sbatch process.batch ./batches/FORECasT_274.json
sbatch process.batch ./batches/FORECasT_275.json
sbatch process.batch ./batches/FORECasT_276.json
sbatch process.batch ./batches/FORECasT_277.json
sbatch process.batch ./batches/FORECasT_278.json
sbatch process.batch ./batches/FORECasT_279.json
sbatch process.batch ./batches/FORECasT_280.json
sbatch process.batch ./batches/FORECasT_281.json
sbatch process.batch ./batches/FORECasT_282.json
sbatch process.batch ./batches/FORECasT_283.json
sbatch process.batch ./batches/FORECasT_284.json
sbatch process.batch ./batches/FORECasT_285.json
sbatch process.batch ./batches/FORECasT_286.json
sbatch process.batch ./batches/FORECasT_287.json
sbatch process.batch ./batches/FORECasT_288.json
sbatch process.batch ./batches/FORECasT_289.json
sbatch process.batch ./batches/FORECasT_290.json
sbatch process.batch ./batches/FORECasT_291.json
sbatch process.batch ./batches/FORECasT_292.json
sbatch process.batch ./batches/FORECasT_293.json
sbatch process.batch ./batches/FORECasT_294.json
sbatch process.batch ./batches/FORECasT_295.json
sbatch process.batch ./batches/FORECasT_296.json
sbatch process.batch ./batches/FORECasT_297.json
sbatch process.batch ./batches/FORECasT_298.json
sbatch process.batch ./batches/FORECasT_299.json
sbatch process.batch ./batches/FORECasT_300.json
sbatch process.batch ./batches/FORECasT_301.json
sbatch process.batch ./batches/FORECasT_302.json
sbatch process.batch ./batches/FORECasT_303.json
sbatch process.batch ./batches/FORECasT_304.json
sbatch process.batch ./batches/FORECasT_305.json
sbatch process.batch ./batches/FORECasT_306.json
sbatch process.batch ./batches/FORECasT_307.json
sbatch process.batch ./batches/FORECasT_308.json
sbatch process.batch ./batches/FORECasT_309.json
sbatch process.batch ./batches/FORECasT_310.json
sbatch process.batch ./batches/FORECasT_311.json
sbatch process.batch ./batches/FORECasT_312.json
sbatch process.batch ./batches/FORECasT_313.json
sbatch process.batch ./batches/FORECasT_314.json
sbatch process.batch ./batches/FORECasT_315.json
sbatch process.batch ./batches/FORECasT_316.json
sbatch process.batch ./batches/FORECasT_317.json
sbatch process.batch ./batches/FORECasT_318.json
sbatch process.batch ./batches/FORECasT_319.json
sbatch process.batch ./batches/FORECasT_320.json
sbatch process.batch ./batches/FORECasT_321.json
sbatch process.batch ./batches/FORECasT_322.json
sbatch process.batch ./batches/FORECasT_323.json
sbatch process.batch ./batches/FORECasT_324.json
sbatch process.batch ./batches/FORECasT_325.json
sbatch process.batch ./batches/FORECasT_326.json
sbatch process.batch ./batches/FORECasT_327.json
sbatch process.batch ./batches/FORECasT_328.json
sbatch process.batch ./batches/FORECasT_329.json
sbatch process.batch ./batches/FORECasT_330.json
sbatch process.batch ./batches/FORECasT_331.json
sbatch process.batch ./batches/FORECasT_332.json
sbatch process.batch ./batches/FORECasT_333.json
sbatch process.batch ./batches/FORECasT_334.json
sbatch process.batch ./batches/FORECasT_335.json
sbatch process.batch ./batches/FORECasT_336.json
sbatch process.batch ./batches/FORECasT_337.json
sbatch process.batch ./batches/FORECasT_338.json
sbatch process.batch ./batches/FORECasT_339.json
sbatch process.batch ./batches/FORECasT_340.json
sbatch process.batch ./batches/FORECasT_341.json
sbatch process.batch ./batches/FORECasT_342.json
sbatch process.batch ./batches/FORECasT_343.json
sbatch process.batch ./batches/FORECasT_344.json
sbatch process.batch ./batches/FORECasT_345.json
sbatch process.batch ./batches/FORECasT_346.json
sbatch process.batch ./batches/FORECasT_347.json
sbatch process.batch ./batches/FORECasT_348.json
sbatch process.batch ./batches/FORECasT_349.json
sbatch process.batch ./batches/FORECasT_350.json
sbatch process.batch ./batches/FORECasT_351.json
sbatch process.batch ./batches/FORECasT_352.json
sbatch process.batch ./batches/FORECasT_353.json
sbatch process.batch ./batches/FORECasT_354.json
sbatch process.batch ./batches/FORECasT_355.json
sbatch process.batch ./batches/FORECasT_356.json
sbatch process.batch ./batches/FORECasT_357.json
sbatch process.batch ./batches/FORECasT_358.json
sbatch process.batch ./batches/FORECasT_359.json
sbatch process.batch ./batches/FORECasT_360.json
sbatch process.batch ./batches/FORECasT_361.json
sbatch process.batch ./batches/FORECasT_362.json
sbatch process.batch ./batches/FORECasT_363.json
sbatch process.batch ./batches/FORECasT_364.json
sbatch process.batch ./batches/FORECasT_365.json
sbatch process.batch ./batches/FORECasT_366.json
sbatch process.batch ./batches/FORECasT_367.json
sbatch process.batch ./batches/FORECasT_368.json
sbatch process.batch ./batches/FORECasT_369.json
sbatch process.batch ./batches/FORECasT_370.json
sbatch process.batch ./batches/FORECasT_371.json
sbatch process.batch ./batches/FORECasT_372.json
sbatch process.batch ./batches/FORECasT_373.json
sbatch process.batch ./batches/FORECasT_374.json
sbatch process.batch ./batches/FORECasT_375.json
sbatch process.batch ./batches/FORECasT_376.json
sbatch process.batch ./batches/FORECasT_377.json
sbatch process.batch ./batches/FORECasT_378.json
sbatch process.batch ./batches/FORECasT_379.json
sbatch process.batch ./batches/FORECasT_380.json
sbatch process.batch ./batches/FORECasT_381.json
sbatch process.batch ./batches/FORECasT_382.json
sbatch process.batch ./batches/FORECasT_383.json
sbatch process.batch ./batches/FORECasT_384.json
sbatch process.batch ./batches/FORECasT_385.json
sbatch process.batch ./batches/FORECasT_386.json
sbatch process.batch ./batches/FORECasT_387.json
sbatch process.batch ./batches/FORECasT_388.json
sbatch process.batch ./batches/FORECasT_389.json
sbatch process.batch ./batches/FORECasT_390.json
sbatch process.batch ./batches/FORECasT_391.json
sbatch process.batch ./batches/FORECasT_392.json
sbatch process.batch ./batches/FORECasT_393.json
sbatch process.batch ./batches/FORECasT_394.json
sbatch process.batch ./batches/FORECasT_395.json
sbatch process.batch ./batches/FORECasT_396.json
sbatch process.batch ./batches/FORECasT_397.json
sbatch process.batch ./batches/FORECasT_398.json
sbatch process.batch ./batches/FORECasT_399.json
sbatch process.batch ./batches/FORECasT_400.json
sbatch process.batch ./batches/FORECasT_401.json
sbatch process.batch ./batches/FORECasT_402.json
sbatch process.batch ./batches/FORECasT_403.json
sbatch process.batch ./batches/FORECasT_404.json
sbatch process.batch ./batches/FORECasT_405.json
sbatch process.batch ./batches/FORECasT_406.json
sbatch process.batch ./batches/FORECasT_407.json
sbatch process.batch ./batches/FORECasT_408.json
sbatch process.batch ./batches/FORECasT_409.json
sbatch process.batch ./batches/FORECasT_410.json
sbatch process.batch ./batches/FORECasT_411.json
sbatch process.batch ./batches/FORECasT_412.json
sbatch process.batch ./batches/FORECasT_413.json
sbatch process.batch ./batches/FORECasT_414.json
sbatch process.batch ./batches/FORECasT_415.json
sbatch process.batch ./batches/FORECasT_416.json
sbatch process.batch ./batches/FORECasT_417.json
sbatch process.batch ./batches/FORECasT_418.json
sbatch process.batch ./batches/FORECasT_419.json
sbatch process.batch ./batches/FORECasT_420.json
sbatch process.batch ./batches/FORECasT_421.json
sbatch process.batch ./batches/FORECasT_422.json
sbatch process.batch ./batches/FORECasT_423.json
sbatch process.batch ./batches/FORECasT_424.json
sbatch process.batch ./batches/FORECasT_425.json
sbatch process.batch ./batches/FORECasT_426.json
sbatch process.batch ./batches/FORECasT_427.json
sbatch process.batch ./batches/FORECasT_428.json
sbatch process.batch ./batches/FORECasT_429.json
sbatch process.batch ./batches/FORECasT_430.json
sbatch process.batch ./batches/FORECasT_431.json
sbatch process.batch ./batches/FORECasT_432.json
sbatch process.batch ./batches/FORECasT_433.json
sbatch process.batch ./batches/FORECasT_434.json
sbatch process.batch ./batches/FORECasT_435.json
sbatch process.batch ./batches/FORECasT_436.json
sbatch process.batch ./batches/FORECasT_437.json
sbatch process.batch ./batches/FORECasT_438.json
sbatch process.batch ./batches/FORECasT_439.json
sbatch process.batch ./batches/FORECasT_440.json
sbatch process.batch ./batches/FORECasT_441.json
sbatch process.batch ./batches/FORECasT_442.json
sbatch process.batch ./batches/FORECasT_443.json
sbatch process.batch ./batches/FORECasT_444.json
sbatch process.batch ./batches/FORECasT_445.json
sbatch process.batch ./batches/FORECasT_446.json
sbatch process.batch ./batches/FORECasT_447.json
sbatch process.batch ./batches/FORECasT_448.json
sbatch process.batch ./batches/FORECasT_449.json
sbatch process.batch ./batches/FORECasT_450.json
sbatch process.batch ./batches/FORECasT_451.json
sbatch process.batch ./batches/FORECasT_452.json
sbatch process.batch ./batches/FORECasT_453.json
sbatch process.batch ./batches/FORECasT_454.json
sbatch process.batch ./batches/FORECasT_455.json
sbatch process.batch ./batches/FORECasT_456.json
sbatch process.batch ./batches/FORECasT_457.json
sbatch process.batch ./batches/FORECasT_458.json
sbatch process.batch ./batches/FORECasT_459.json
sbatch process.batch ./batches/FORECasT_460.json
sbatch process.batch ./batches/FORECasT_461.json
sbatch process.batch ./batches/FORECasT_462.json
sbatch process.batch ./batches/FORECasT_463.json
sbatch process.batch ./batches/FORECasT_464.json
sbatch process.batch ./batches/FORECasT_465.json
sbatch process.batch ./batches/FORECasT_466.json
sbatch process.batch ./batches/FORECasT_467.json
sbatch process.batch ./batches/FORECasT_468.json
sbatch process.batch ./batches/FORECasT_469.json
sbatch process.batch ./batches/FORECasT_470.json
sbatch process.batch ./batches/FORECasT_471.json
sbatch process.batch ./batches/FORECasT_472.json
sbatch process.batch ./batches/FORECasT_473.json
sbatch process.batch ./batches/FORECasT_474.json
sbatch process.batch ./batches/FORECasT_475.json
sbatch process.batch ./batches/FORECasT_476.json
sbatch process.batch ./batches/FORECasT_477.json
sbatch process.batch ./batches/FORECasT_478.json
sbatch process.batch ./batches/FORECasT_479.json
sbatch process.batch ./batches/FORECasT_480.json
sbatch process.batch ./batches/FORECasT_481.json
sbatch process.batch ./batches/FORECasT_482.json
sbatch process.batch ./batches/FORECasT_483.json
sbatch process.batch ./batches/FORECasT_484.json
sbatch process.batch ./batches/FORECasT_485.json
sbatch process.batch ./batches/FORECasT_486.json
sbatch process.batch ./batches/FORECasT_487.json
sbatch process.batch ./batches/FORECasT_488.json
sbatch process.batch ./batches/FORECasT_489.json
sbatch process.batch ./batches/FORECasT_490.json
sbatch process.batch ./batches/FORECasT_491.json
sbatch process.batch ./batches/FORECasT_492.json
sbatch process.batch ./batches/FORECasT_493.json
sbatch process.batch ./batches/FORECasT_494.json
sbatch process.batch ./batches/FORECasT_495.json
sbatch process.batch ./batches/FORECasT_496.json
sbatch process.batch ./batches/FORECasT_497.json
sbatch process.batch ./batches/FORECasT_498.json
sbatch process.batch ./batches/FORECasT_499.json
